### ISSUE TITLE
Some mistakes in uploaded xml

### ISSUE THREAD

**Issue by FireRaiser13** [olegabu/nsd-commercial-paper-client#2]
In the downloaded xml-file:
1.	There is an extra space in the tag <based_ date> after underline
2.	There are two empty rows before based document's block and after them
3.	There is no first row ?xml version="1.0" encoding="Windows-1251"?
Example (xml) u can see in Mark's letter

**Comment by olegabu** [comment]
После моего письма нам удалось протестировать загрузку тестовых xml в Аламеду С и БЕЗ строки encoding:
Без - русские символы в блоке Based нечитаемы. 

Надо добавлять строку
>
>          <?xml version="1.0" encoding="Windows-1251"?>
>
при формировании xml в блокчейн.

С уважением,
Марк Сердюков
